# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# --- SMART HISTORY CONFIG ---

# 1. Size: Keep a lot, but not infinity
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# 2. No Duplicates (The Fix for your main complaint)
# If you run 'docker ps' today, it deletes the entry from yesterday.
# You only ever see the command ONCE in your list (the most recent time).
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_FIND_NO_DUPS
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST

# 3. Ignore "Junk" Commands automatically
# This stops 'ls', 'cd', 'pwd', and 'exit' from cluttering your history.
# You can add more separated by |
HISTORY_IGNORE="(ls|ll|cd|pwd|exit|clear|reboot|history)"

# 4. The "Spy Mode" (Ignore Space)
# If you type a SPACE before a command, it will NOT be saved.
# Example: " <space> echo my_password" -> Won't appear in history.
setopt HIST_IGNORE_SPACE

# 5. Share history instantly
# If you have two terminals open, they share history immediately.
setopt SHARE_HISTORY

# To access the data folder with $assets
export assets="/srv/data/assets"

# --- CTRL+BACKSPACE FIX ---

# 1. Set "Word Style" to Bash
# This tells Zsh that only letters/numbers are words.
# Everything else (/ . -) is a separator.
autoload -U select-word-style
select-word-style bash

# 2. Bind the Key
# '^H' is the standard code sent by terminals for Ctrl+Backspace
bindkey '^H' backward-kill-word

# 3. Alternative code (Some terminals send this instead)
bindkey '^[[3;5~' backward-kill-word

# --- INTELLIGENT UP/DOWN SEARCH ---

# 1. Load the required functions
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# 2. Bind the Arrow Keys
# This maps "Up Arrow" to the search function
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

# 3. Alternative Codes (For Termux/different terminals)
# If the above doesn't work, one of these usually covers the rest:
bindkey '^[[OA' up-line-or-beginning-search
bindkey '^[[OB' down-line-or-beginning-search

# Universal Extract Function
extract () {
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1     ;;
      *.tar.gz)    tar xzf $1     ;;
      *.bz2)       bunzip2 $1     ;;
      *.rar)       unrar e $1     ;;
      *.gz)        gunzip $1      ;;
      *.tar)       tar xf $1      ;;
      *.tbz2)      tar xjf $1     ;;
      *.tgz)       tar xzf $1     ;;
      *.zip)       unzip $1       ;;
      *.Z)         uncompress $1  ;;
      *.7z)        7z x $1        ;;
      *.tar.xz)    tar xJf $1     ;;  # <--- The one we used for your backups
      *)           echo "'$1' cannot be extracted via extract()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# Enable FZF (Fuzzy Finder) Keybindings
# This turns on Ctrl+R (History) and Ctrl+T (File Search)
[ -f /usr/share/doc/fzf/examples/key-bindings.zsh ] && source /usr/share/doc/fzf/examples/key-bindings.zsh
[ -f /usr/share/doc/fzf/examples/completion.zsh ] && source /usr/share/doc/fzf/examples/completion.zsh

# Git auto-commit warning
typeset -A _visited_zones

chpwd() {
    # 1. Check if warning file exists
    if [ -f .commit-warning ]; then
        
        # 2. Check if we have ALREADY seen this specific folder in this session
        if [ -z "${_visited_zones[$PWD]}" ]; then
            
            echo ""
            echo -e "\033[1;41;37m ⚠️  GIT AUTO-COMMIT ZONE ⚠️ \033[0m"
            echo -e "\033[1;31m" 
            
            # Print the warning (ignoring comments and empty lines)
            grep -Ev "^#|^\s*$" .commit-warning
            
            echo -e "\033[0m"
            echo ""

            # 3. Mark this folder as 'visited' so it doesn't show again this session
            _visited_zones[$PWD]=1
        fi
    fi
}
