#!/usr/bin/env python3
# @DESCRIPTION: Creates a human-readable .MD file of the crontabs
# @FREQUENCY: Daily 5am (triggered by `backup-scripts-git.sh`)
import os
import re # <--- ADDED THIS
from cron_descriptor import get_description, Options

# --- CONFIG ---
SOURCE_DIR = "/home/gravi-ctrl/scripts/run_once/system_configs"
OUTPUT_FILE = "/home/gravi-ctrl/scripts/run_once/system_configs/CRON_SCHEDULE.md"

# Options for the translator
opts = Options()
opts.use_24hour_time_format = True

def parse_crontab(filename, title):
    content = []
    file_path = os.path.join(SOURCE_DIR, filename)

    if not os.path.exists(file_path):
        return []

    content.append(f"## {title}")
    content.append("| Task Name / Description | Frequency | Command |")
    content.append("| :--- | :--- | :--- |")

    with open(file_path, 'r') as f:
        lines = f.readlines()

    has_entries = False
    last_comment = ""

    # Mapping for %u (1=Mon ... 7=Sun)
    week_map = {
        '1': 'Monday', '2': 'Tuesday', '3': 'Wednesday', 
        '4': 'Thursday', '5': 'Friday', '6': 'Saturday', '7': 'Sunday'
    }

    for line in lines:
        line = line.strip()

        # 1. Skip Empty Lines
        if not line:
            last_comment = ""
            continue

        # 2. Capture Comments
        if line.startswith("#"):
            last_comment = line.lstrip("#").strip()
            continue

        # 3. Detect Cron Jobs
        if line[0].isdigit() or line[0] == '*' or line.startswith("@"):
            raw_schedule = ""
            command = ""
            human_desc = ""

            try:
                # SCENARIO A: Special (@reboot)
                if line.startswith("@"):
                    parts = line.split(maxsplit=1)
                    if len(parts) == 2:
                        raw_schedule = parts[0]
                        command = parts[1]
                        human_desc = "On System Event"
                    else:
                        command = line
                        human_desc = "Unknown"

                # SCENARIO B: Standard
                else:
                    parts = line.split(maxsplit=5)
                    if len(parts) >= 6:
                        raw_schedule = " ".join(parts[:5])
                        command = parts[5]

                        try:
                            human_desc = get_description(raw_schedule, opts)
                        except:
                            human_desc = f"`{raw_schedule}`"
                    else:
                        command = line
                        human_desc = "⚠️ Invalid Format"

                # -----------------------------------------------------------
                # ### CUSTOM LOGIC: Detect Bash Date Conditionals ###
                # Detects: [ "$(date +\%u)" = 5 ] && command
                # -----------------------------------------------------------
                if command:
                    # Regex looks for: [ "$(date +\%u)" = X ]
                    # It handles spaces, different quotes, and the escaped %
                    match = re.match(r'^\[\s*"\$\(date \+\\%u\)"\s*=\s*([1-7])\s*\]\s*&&\s*(.*)', command)
                    
                    if match:
                        day_num = match.group(1)   # The number (e.g., "5")
                        real_cmd = match.group(2)  # The rest of the command
                        
                        day_name = week_map.get(day_num, "Unknown Day")
                        
                        # Update the Human Description
                        human_desc += f" <br>**(⚠️ Condition: Only on {day_name}s)**"
                        
                        # Optional: Clean the command in the table to show the REAL script
                        # or keep the full logic. Below keeps the logic but makes it code.
                        # If you want to show ONLY the script, uncomment the next line:
                        # command = real_cmd 

                # 4. Format the Table Row
                if command:
                    task_name = f"**{last_comment}**" if last_comment else ""
                    safe_command = command.replace("|", "\\|")
                    
                    if len(safe_command) > 120:
                        safe_command = safe_command[:117] + "..."

                    content.append(f"| {task_name} | {human_desc} | `{safe_command}` |")
                    has_entries = True
                    last_comment = ""

            except Exception as e:
                content.append(f"| ⚠️ Error | Could not parse | `{line}` |")

    if not has_entries:
        content.append("*No active jobs found.*")

    content.append("\n")
    return content

# --- MAIN EXECUTION ---
final_md = [
    "# 📅 System Automation Schedule",
    "> 🤖 Auto-generated by `cron_translator.py`",
    ""
]

final_md.extend(parse_crontab("user_crontab.txt", "👤 User Cron (gravi-ctrl)"))
final_md.extend(parse_crontab("root_crontab.txt", "⚡ Root Cron"))

with open(OUTPUT_FILE, 'w') as f:
    f.write("\n".join(final_md))

print(f"Schedule generated at: {OUTPUT_FILE}")
