#!/usr/bin/env python3
# @DESCRIPTION: Creates a human-readable file of every script and its function
# @FREQUENCY: Daily 5am (triggered by `backup-scripts-git.sh`)
import os
from pathlib import Path

# --- CONFIG ---
ROOT_DIR = "/home/gravi-ctrl/scripts"
OUTPUT_FILE = "/home/gravi-ctrl/scripts/SCRIPTS_INVENTORY.md"
IGNORE_DIRS = [".git", "venv", "__pycache__", "ctrl_s_master"] # Skip these folders
EXTENSIONS = {".sh", ".py"}

def get_metadata(file_path):
    desc = "No description provided."
    freq = "On Demand"
    
    try:
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            # Read first 20 lines only (Metadata should be at top)
            for _ in range(20):
                line = f.readline().strip()
                if not line: continue
                
                # Look for magic tags (case insensitive)
                upper_line = line.upper()
                if "@DESCRIPTION:" in upper_line:
                    desc = line.split(":", 1)[1].strip()
                elif "@FREQUENCY:" in upper_line:
                    freq = line.split(":", 1)[1].strip()
    except:
        pass
        
    return desc, freq

def generate_inventory():
    inventory = []
    
    # Walk through all folders
    for root, dirs, files in os.walk(ROOT_DIR):
        # Filter ignored directories
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]
        
        for file in files:
            file_path = Path(root) / file
            
            # Skip non-scripts
            if file_path.suffix not in EXTENSIONS:
                continue
                
            desc, freq = get_metadata(file_path)
            
            # Make path relative for cleaner display (e.g., "wifi_robot/main.py")
            rel_path = file_path.relative_to(ROOT_DIR)
            
            inventory.append({
                "script": str(rel_path),
                "desc": desc,
                "freq": freq
            })

    # Sort alphabetically
    inventory.sort(key=lambda x: x['script'])
    
    # Build Markdown
    md = [
        "# 📂 Script Inventory",
        "> 🤖 Auto-generated by `script_indexer.py`",
        "",
        "| Script File | Purpose | Frequency |",
        "| :--- | :--- | :--- |"
    ]
    
    for item in inventory:
        # Link to the file in GitHub (assuming repo structure matches)
        md.append(f"| `{item['script']}` | {item['desc']} | {item['freq']} |")
        
    with open(OUTPUT_FILE, 'w') as f:
        f.write("\n".join(md))
        
    print(f"Inventory generated: {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_inventory()
