#!/usr/bin/env python3
# @DESCRIPTION: Creates a human-readable .MD file of every script and its function
# @FREQUENCY: Daily 5am (triggered by `backup-scripts-git.sh`)
import os
import collections
import getpass
from pathlib import Path

# Get the Root Dir
ROOT_DIR = os.path.dirname(os.path.realpath(__file__))
OUTPUT_FILE = os.path.join(ROOT_DIR, "SCRIPTS_INVENTORY.md")
# Gets the current user for the metadata
BACKUP_USER = getpass.getuser()
EXTENSIONS = {".sh", ".py"}

def is_script_file(file_path):
    if file_path.suffix in EXTENSIONS:
        return True

    if file_path.suffix == "":
        try:
            with open(file_path, 'rb') as f:
                return f.read(2) == b'#!'
        except:
            return False

    return False

def get_metadata(file_path):
    desc = None
    freq = None

    try:
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            for _ in range(20):
                line = f.readline().strip()
                if not line: continue

                upper_line = line.upper()
                if "@DESCRIPTION:" in upper_line:
                    desc = line.split(":", 1)[1].strip()
                elif "@FREQUENCY:" in upper_line:
                    freq = line.split(":", 1)[1].strip()
    except:
        pass

    return desc, freq

def generate_inventory():
    # Use a dictionary to group scripts by their folder
    categorized_inventory = collections.defaultdict(list)
    undocumented =[]

    for root, _, files in os.walk(ROOT_DIR):
        for file in files:
            file_path = Path(root) / file
            if not is_script_file(file_path): continue

            desc, freq = get_metadata(file_path)
            rel_path = file_path.relative_to(ROOT_DIR)

            if desc is None or freq is None:
                undocumented.append(str(rel_path))
                continue

            # Group by parent folder name (or 'Root' if in main folder)
            category = rel_path.parent.name if rel_path.parent.name else "Core Scripts"
            categorized_inventory[category].append({
                "script": file,
                "desc": desc,
                "freq": freq,
                "full_path": str(rel_path)
            })

    md =[
        "# 📂 Script Inventory",
        "> 🤖 Auto-generated by `script_indexer.py`\n"
    ]

    # Generate a table for each category
    for category in sorted(categorized_inventory.keys()):
        md.append(f"### 📁 {category.title()}")
        md.append("| Script File | Purpose | Frequency |")
        md.append("| :--- | :--- | :--- |")

        for item in sorted(categorized_inventory[category], key=lambda x: x['script']):
            md.append(f"| `{item['full_path']}` | {item['desc']} | {item['freq']} |")
        md.append("\n")

    # The "Wall of Shame"
    if undocumented:
        md.append("## ⚠️ Undocumented Scripts")
        md.append("> *These scripts are missing `@DESCRIPTION:` or `@FREQUENCY:` tags.*")
        for u in sorted(undocumented):
            md.append(f"- `{u}`")

    with open(OUTPUT_FILE, 'w') as f:
        f.write("\n".join(md))

    print(f"Inventory generated: {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_inventory()
