#!/bin/bash
# @DESCRIPTION: A Telegram alert gets sent when any job in crontab fails
# @FREQUENCY: On Failure

# INSTALL
# -------
# sudo cp tg-alert /usr/local/bin
# sudo chmod +x /usr/local/bin/tg-alert
# USAGE: At the end of any job in crontab, we can add something like '|| /usr/local/bin/tg-alert "message_here"'
# So if command X fails send a telegram message saying 'CRON FAILURE: message_here'

set -e
set -o pipefail

# Your Bot Credentials
TOKEN="TELEGRAM_BOT_TOKEN"
CHAT_ID="YOUR_CHAT_ID"

# The message comes from the argument you pass
JOB_NAME="$1"

# Send the message
curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
    -d chat_id="$CHAT_ID" \
    -d text="⚠️ CRON FAILURE: $JOB_NAME" > /dev/null
