#!/bin/bash

# cp the script to /usr/local/bin (which should be in $PATH)
# make it executable chmod +x tg-alert

set -e
set -o pipefail

# Your Bot Credentials
TOKEN="TELEGRAM_BOT_TOKEN"
CHAT_ID="YOUR_CHAT_ID"

# The message comes from the argument you pass
JOB_NAME="$1"

# Send the message
curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
    -d chat_id="$CHAT_ID" \
    -d text="⚠️ CRON FAILURE: $JOB_NAME" > /dev/null
